apiVersion: v1
kind: Service
metadata:
  name: my-java-app-service
spec:
  selector:
    app: my-java-app
  ports:
  - protocol: TCP
    port: 80        # internal cluster port
    targetPort: 8080
    nodePort: 30007
  type: NodePort
